const ORDERSTATUS_LIST = "ORDERSTATUS_LIST";
const ORDERSTATUS_LOADING = "ORDERSTATUS_LOADING";
const ORDERSTATUS_DONE = "ORDERSTATUS_DONE";
const ORDERSTATUS_ERROR = "ORDERSTATUS_ERROR";
export default {
  ORDERSTATUS_LIST,
  ORDERSTATUS_LOADING,
  ORDERSTATUS_DONE,
  ORDERSTATUS_ERROR
};
