// product add
export const PRODUCT_PRODUCT_ADD_CHANGE_PROP = 'PRODUCT_PRODUCT_ADD_CHANGE_PROP';
export const PRODUCT_PRODCUT_ADD_FETCH_CATEGORIES = 'PRODUCT_PRODCUT_ADD_FETCH_CATEGORIES';
export const PRODUCT_PRODUCT_ADD_RESET_FORM = 'PRODUCT_PRODUCT_ADD_RESET_FORM';

// product edit 
export const PRODUCT_PRODUCT_EDIT_CHANGE_PROP = 'PRODUCT_PRODUCT_EDIT_CHANGE_PROP';
export const PRODUCT_PRODCUT_EDIT_FETCH_CATEGORIES = 'PRODUCT_PRODCUT_EDIT_FETCH_CATEGORIES';
export const PRODUCT_PRODUCT_EDIT_RESET_FORM = 'PRODUCT_PRODUCT_EDIT_RESET_FORM';
export const PRODUCT_PRODUCT_EDIT_SET_FORM = 'PRODUCT_PRODUCT_EDIT_SET_FORM';

// product list
export const PRODUCT_PRODUCT_LIST_SET_PRODUCTS = 'PRODUCT_PRODUCT_LIST_SET_PRODUCTS';