// Campain list
export const CAMPIAN_CAMPAIN_LIST_CHANGE_PROP = 'CAMPIAN_CAMPAIN_LIST_CHANGE_PROP';
export const CAMPIAN_CAMPAIN_LIST_CHANGE_GIFT_PROP = 'CAMPIAN_CAMPAIN_LIST_CHANGE_GIFT_PROP';
export const CAMPIAN_CAMPAIN_LIST_RESET_FORM = 'CAMPIAN_CAMPAIN_LIST_CHANGE_RESET_FORM';