// Campain add 
export const CAMPIAN_CAMPAIN_ADD_CHANGE_PROP = 'CAMPIAN_CAMPAIN_ADD_CHANGE_PROP';
export const CAMPIAN_CAMPAIN_ADD_CHANGE_GIFT_PROP = 'CAMPIAN_CAMPAIN_ADD_CHANGE_GIFT_PROP';
export const CAMPIAN_CAMPAIN_ADD_RESET_FORM = 'CAMPIAN_CAMPAIN_ADD_CHANGE_RESET_FORM'