// Campain add 
export const CAMPIAN_CAMPAIN_ADD_CHANGE_PROP = 'CAMPIAN_CAMPAIN_ADD_CHANGE_PROP';
export const CAMPIAN_CAMPAIN_ADD_CHANGE_GIFT_PROP = 'CAMPIAN_CAMPAIN_ADD_CHANGE_GIFT_PROP';
export const CAMPIAN_CAMPAIN_ADD_RESET_FORM = 'CAMPIAN_CAMPAIN_ADD_CHANGE_RESET_FORM'
export const CAMPAIN_CAMPAIN_ADD_TOGGLE_PRODUCT_DIALOG = 'CAMPAIN_CAMPAIN_ADD_TOGGLE_PRODUCT_DIALOG';
export const CAMPAIN_CAMPAIN_ADD_FETCH_PRODUCTS = 'CAMPAIN_CAMPAIN_ADD_FETCH_PRODUCTS';
export const CAMPAIN_CAMPAIN_ADD_SET_GIFT = 'CAMPAIN_CAMPAIN_ADD_SET_GIFT';

// Campain list
export const CAMPAIN_CAMPAIN_LIST_FETCH_CAMPAINS = 'CAMPAIN_CAMPAIN_LIST_FETCH_CAMPAINS';
export const CAMPAIN_CAMPAIN_LIST_CHANGE_PROP = 'CAMPAIN_CAMPAIN_LIST_CHANGE_PROP';