const CHECKLIST_ADD = "CHECKLIST_ADD";
const CHECKLIST_EDIT = "CHECKLIST_EDIT";
const CHECKLIST_DELETE = "CHECKLIST_DELETE";
const CHECKLIST_LIST = "CHECKLIST_LIST";
const PARENT_CHECKLIST_LIST = "PARENT_CHECKLIST_LIST";
const CHECKLIST_LOADING = "CHECKLIST_LOADING";
const CHECKLIST_DONE = "CHECKLIST_DONE";
const CHECKLIST_ERROR = "CHECKLIST_ERROR";
export default {
  CHECKLIST_ADD,
  CHECKLIST_EDIT,
  CHECKLIST_DELETE,
  CHECKLIST_LIST,
  CHECKLIST_LOADING,
  CHECKLIST_DONE,
  PARENT_CHECKLIST_LIST,
  CHECKLIST_ERROR
};
