// plugins shop
export const PLUGINS_PLUGINS_SHOP_TOGGLE_PLUGIN_DIALOG = 'PLUGINS_PLUGINS_SHOP_TOGGLE_PLUGIN_DIALOG';

// my plugins
export const PLUGINS_MY_PLUGINS_TOGGLE_PLUGIN_DIALOG = 'PLUGINS_MY_PLUGINS_TOGGLE_PLUGIN_DIALOG';