// plugins shop
export const PLUGINS_PLUGINS_SHOP_TOGGLE_PLUGIN_DIALOG = 'PLUGINS_PLUGINS_SHOP_TOGGLE_PLUGIN_DIALOG';
export const PLUGINS_PLUGINS_SHOP_FETCH_PLUGINS = 'PLUGINS_PLUGINS_SHOP_FETCH_PLUGINS';

// my plugins
export const PLUGINS_MY_PLUGINS_TOGGLE_PLUGIN_DIALOG = 'PLUGINS_MY_PLUGINS_TOGGLE_PLUGIN_DIALOG';