// plugins shop
export const PLUGINS_PLUGINS_SHOP_TOGGLE_PLUGIN_DIALOG = 'PLUGINS_PLUGINS_SHOP_TOGGLE_PLUGIN_DIALOG';
export const PLUGINS_PLUGINS_SHOP_FETCH_PLUGINS = 'PLUGINS_PLUGINS_SHOP_FETCH_PLUGINS';
export const PLUGINS_PLUGINS_SHOP_SET_SELECTED_PLUGIN = 'PLUGINS_PLUGINS_SHOP_SET_SELECTED_PLUGIN';

// my plugins
export const PLUGINS_MY_PLUGINS_TOGGLE_PLUGIN_DIALOG = 'PLUGINS_MY_PLUGINS_TOGGLE_PLUGIN_DIALOG';