// category add
export const CATEGORY_CATEGORY_ADD_CHANGE_PROP = 'CATEGORY_CATEGORY_ADD_CHANGE_PROP';
export const CATEGORY_CATEGORY_ADD_FETCH_CATEGORIES = 'CATEGORY_CATEGORY_ADD_FETCH_CATEGORIES';
export const CATEGORY_CATEGORY_ADD_RESET_FORM = 'CATEGORY_CATEGORY_ADD_RESET_FORM';

// category list
export const CATEGORY_CATEGORY_LIST_FETCH_CATEGORIES = 'CATEGORY_CATEGORY_LIST_FETCH_CATEGORIES';

// category edit 
export const CATEGORY_CATEGORY_EDIT_CHANGE_PROP = 'CATEGORY_CATEGORY_EDIT_CHANGE_PROP';
export const CATEGORY_CATEGORY_EDIT_FETCH_CATEGORIES = 'CATEGORY_CATEGORY_EDIT_FETCH_CATEGORIES';
export const CATEGORY_CATEGORY_EDIT_RESET_FORM = 'CATEGORY_CATEGORY_EDIT_RESET_FORM';
export const CATEGORY_CATEGORY_EDIT_SET_FORM = 'CATEGORY_CATEGORY_EDIT_SET_FORM';