// category add
export const CATEGORY_CATEGORY_ADD_CHANGE_PROP = 'CATEGORY_CATEGORY_ADD_CHANGE_PROP';
export const CATEGORY_CATEGORY_ADD_FETCH_CATEGORIES = 'CATEGORY_CATEGORY_ADD_FETCH_CATEGORIES';
export const CATEGORY_CATEGORY_ADD_RESET_FORM = 'CATEGORY_CATEGORY_ADD_RESET_FORM';