// REGISTER
export const CLUB_REGISTER_PHONE = 'CLUB_REGISTER_PHONE';

// LOGIN VERIFY
export const CLUB_VERIFY_PHONE = 'CLUB_VERIFY_PHONE';
export const CLUB_USER_DATA = 'CLUB_USER_DATA';
export const CLUB_REGISTER_USER_PHONE = 'CLUB_REGISTER_USER_PHONE';
export const CANCEL_CLUB_REGISTER_USER_PHONE = 'CANCEL_CLUB_REGISTER_USER_PHONE';