const ORDER_ADD = "ORDER_ADD";
const ORDER_EDIT = "ORDER_EDIT";
const ORDER_DELETE = "ORDER_DELETE";
const ORDER_LIST = "ORDER_LIST";
const ORDER_LOADING = "ORDER_LOADING";
const ORDER_DONE = "ORDER_DONE";
const ORDER_ERROR = "ORDER_ERROR";
const CUSTOMER_ORDERS = "CUSTOMER_ORDERS";
export default {
  ORDER_ADD,
  ORDER_EDIT,
  ORDER_DELETE,
  ORDER_LIST,
  ORDER_LOADING,
  ORDER_DONE,
  ORDER_ERROR,
  CUSTOMER_ORDERS
};
