const LABEL_ADD = "LABEL_ADD";
const LABEL_EDIT = "LABEL_EDIT";
const LABEL_DELETE = "LABEL_DELETE";
const LABEL_LIST = "LABEL_LIST";
const LABEL_LOADING = "LABEL_LOADING";
const LABEL_DONE = "LABEL_DONE";
export default {
  LABEL_ADD,
  LABEL_EDIT,
  LABEL_DELETE,
  LABEL_LIST,
  LABEL_LOADING,
  LABEL_DONE
};
