// REGISTER
export const AUTH_REGISTER_CHANGE_FORM = 'AUTH_REGISTER_CHANGE_FORM';

// LOGIN VERIFY
export const AUTH_LOGIN_VERIFY_CHANGE_PROP = 'AUTH_LOGIN_VERIFY_CHANGE_PROP ';
export const AUTH_LOGIN_VERIFY_ERROR = 'AUTH_LOGIN_VERIFY_ERROR';