// REGISTER
export const AUTH_REGISTER_CHANGE_FORM = 'AUTH_REGISTER_CHANGE_FORM';
export const AUTH_REGISTER_RESET = 'AUTH_REGISTER_RESET';

// LOGIN VERIFY
export const AUTH_LOGIN_VERIFY_CHANGE_PROP = 'AUTH_LOGIN_VERIFY_CHANGE_PROP ';
export const AUTH_LOGIN_VERIFY_ERROR = 'AUTH_LOGIN_VERIFY_ERROR';
export const AUTH_LOGIN_VERIFY_RESET = 'AUTH_LOGIN_VERIFY_RESET';