// customer list
export const CUSTOMER_CUSTOMER_LIST_FETCH_CUSTOMERS = 'CUSTOMER_CUSTOMER_LIST_FETCH_CUSTOMERS';
export const CUSTOMER_CUSTOMER_LIST_CHANGE_QUERY = 'CUSTOMER_CUSTOMER_LIST_CHANGE_QUERY'

// customer add
export const CUSTOMER_CUSTOMER_ADD_CHANGE_PROP = 'CUSTOMER_CUSTOMER_ADD_CHANGE_PROP';
export const CUSTOMER_CUSTOMER_RESET_FORM = 'CUSTOMER_CUSTOMER_RESET_FORM';