// customer list
export const CUSTOMER_CUSTOMER_LIST_FETCH_CUSTOMERS = 'CUSTOMER_CUSTOMER_LIST_FETCH_CUSTOMERS';
export const CUSTOMER_CUSTOMER_LIST_CHANGE_QUERY = 'CUSTOMER_CUSTOMER_LIST_CHANGE_QUERY'

// customer add
export const CUSTOMER_CUSTOMER_ADD_CHANGE_PROP = 'CUSTOMER_CUSTOMER_ADD_CHANGE_PROP';
export const CUSTOMER_CUSTOMER_ADD_RESET_FORM = 'CUSTOMER_CUSTOMER_RESET_FORM';

// customer edit 
export const CUSTOMER_CUSTOMER_EDIT_CHANGE_PROP = 'CUSTOMER_CUSTOMER_EDIT_CHANGE_PROP';
export const CUSTOMER_CUSTOMER_EDIT_SET_CUSTOMER = 'CUSTOMER_CUSTOMER_EDIT_SET_CUSTOMER';
export const CUSTOMER_CUSTOMER_EDIT_RESET_FORM = 'CUSTOMER_CUSTOMER_EDIT_RESET_FORM';
export const CUSTOMER_MESSAGES_LIST = 'CUSTOMER_MESSAGES_LIST';